app = "red-wood-4254"

[deploy]
	release_command = ""
 	strategy = "immediate"
	primary_region = "iad"

[build]
image = "python:3.11"

[env]
PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"

	[[services.ports]]
	handlers = ["http"]
	port = 80

	[[services.ports]]
	handlers = ["tls", "http"]
	port = 443
