app = "myfastapiapp"  # <-- use your real Fly.io app name here
primary_region = "iad"

[vm]
auto_destroy = false

[build]
image = "python:3.11"

[env]
PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"

  [[services.ports]]
  handlers = ["http"]
  port = 80

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443
